export const USER = "USER";
export const REMOVE_USER = "REMOVE_USER";
export const RESERVATION_DATES = "RESERVATION_DATES";
export const REMOVE_RESERVATION_DATES = "REMOVE_RESERVATION_DATES";
export const RESERVATIONS = "RESERVATIONS";